# Site settings
title: Incurations
email: hello@incurations.com
url: https://incurations.github.io
description: "Web base data and information solutions."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Incurations
  location: 
  social: 
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 306 W. Vine St.
  - line: Champaign, IL 61820

# Credits content
credits: 

# Build settings
markdown: kramdown
permalink: pretty
